name: Test DOT CI

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome
